# Numpy Trigonometric Functions

### Vòng tròn lượng giác

Vòng tròn lượng giác là một công cụ hữu ích để mô tả các hàm lượng giác như **sin**, **cos**, **tan**, và các hàm nghịch đảo của chúng. Nó là một vòng tròn có bán kính bằng 1, và được sử dụng để mô tả các giá trị của các hàm lượng giác tương ứng với các góc trong một hệ tọa độ vuông góc.

---

### Cấu trúc của vòng tròn lượng giác:

1. **Tọa độ của điểm trên vòng tròn**:

   * Vòng tròn lượng giác có tâm tại gốc tọa độ $(0,0)$ và bán kính bằng 1.
   * Một điểm bất kỳ trên vòng tròn lượng giác có tọa độ $(x, y)$, trong đó:

     * **x** là giá trị **cosine** của góc.
     * **y** là giá trị **sine** của góc.
   * Tọa độ của điểm trên vòng tròn có thể được biểu diễn như sau: $(\cos(\theta), \sin(\theta))$, trong đó $\theta$ là góc mà tia từ gốc tọa độ tạo với trục hoành.

2. **Góc và vị trí trên vòng tròn**:

   * Góc $\theta$ được đo từ trục hoành dương (trục x) theo chiều kim đồng hồ (đối với góc âm) hoặc ngược chiều kim đồng hồ (đối với góc dương).
   * Các giá trị của **sin** và **cos** thay đổi khi góc $\theta$ thay đổi.

---

### Các hàm lượng giác trong vòng tròn lượng giác:

1. **Sin và Cos**:

   * **Cos($\theta$)** là hoành độ (x) của điểm trên vòng tròn.
   * **Sin($\theta$)** là tung độ (y) của điểm trên vòng tròn.

   Khi góc $\theta$ thay đổi, **sin($\theta$)** và **cos($\theta$)** thay đổi theo vị trí của điểm trên vòng tròn.

   * **Ví dụ**: Nếu $\theta = 0^\circ$ (góc này tương ứng với điểm trên trục hoành dương), ta có:

     $$
     \cos(0^\circ) = 1, \quad \sin(0^\circ) = 0
     $$

     * Nếu $\theta = 90^\circ$ (góc này tương ứng với điểm trên trục tung dương), ta có:

     $$
     \cos(90^\circ) = 0, \quad \sin(90^\circ) = 1
     $$

2. **Tan**:

   * **Tan($\theta$)** là tỉ số giữa **sin($\theta$)** và **cos($\theta$)**:

     $$
     \tan(\theta) = \frac{\sin(\theta)}{\cos(\theta)}
     $$
   * Tan không xác định khi $\cos(\theta) = 0$ (tức là tại góc $90^\circ$ và $270^\circ$).

---

### Các hàm nghịch đảo trong vòng tròn lượng giác:

1. **Arcsin ($\arcsin(x)$)**:

   * $\arcsin(x)$ trả về góc $\theta$ sao cho **sin($\theta$) = x**.
   * Trong vòng tròn lượng giác, $x$ là tung độ của điểm, và $\arcsin(x)$ cho phép bạn xác định góc từ giá trị này.
   * **Giới hạn**: $\arcsin(x)$ có giá trị trong khoảng $-\frac{\pi}{2}$ đến $\frac{\pi}{2}$ (hoặc -90° đến 90°).

2. **Arccos ($\arccos(x)$)**:

   * $\arccos(x)$ trả về góc $\theta$ sao cho **cos($\theta$) = x**.
   * Trong vòng tròn lượng giác, $x$ là hoành độ của điểm, và $\arccos(x)$ cho phép bạn xác định góc từ giá trị này.
   * **Giới hạn**: $\arccos(x)$ có giá trị trong khoảng $0$ đến $\pi$ (hoặc 0° đến 180°).

3. **Arctan ($\arctan(x)$)**:

   * $\arctan(x)$ trả về góc $\theta$ sao cho **tan($\theta$) = x**.
   * **Giới hạn**: $\arctan(x)$ có giá trị trong khoảng $-\frac{\pi}{2}$ đến $\frac{\pi}{2}$ (hoặc -90° đến 90°).

---

### Tóm tắt mối quan hệ trong vòng tròn lượng giác:

* **Sin** và **Cos** liên quan đến các tọa độ của điểm trên vòng tròn.
* **Tan** là tỉ số giữa **sin** và **cos**, vì vậy nó liên quan đến tỉ số giữa tung độ và hoành độ của điểm trên vòng tròn.
* Các hàm nghịch đảo như **arcsin**, **arccos**, **arctan** cho phép ta tìm góc khi biết giá trị của sin, cos hoặc tan.

### Ví dụ minh họa trên vòng tròn lượng giác:

* **Góc 0°** (hoặc 0 radians):

  $$
  \cos(0^\circ) = 1, \quad \sin(0^\circ) = 0
  $$
* **Góc 90°** (hoặc $\frac{\pi}{2}$ radians):

  $$
  \cos(90^\circ) = 0, \quad \sin(90^\circ) = 1
  $$
* **Góc 180°** (hoặc $\pi$ radians):

  $$
  \cos(180^\circ) = -1, \quad \sin(180^\circ) = 0
  $$
* **Góc 270°** (hoặc $\frac{3\pi}{2}$ radians):

  $$
  \cos(270^\circ) = 0, \quad \sin(270^\circ) = -1
  $$

Vòng tròn lượng giác giúp bạn dễ dàng hình dung sự thay đổi của các hàm lượng giác khi góc thay đổi, và là nền tảng quan trọng trong các ứng dụng toán học, vật lý, kỹ thuật và nhiều lĩnh vực khác.


#### Trigonometric Functions
+ Numpy provides the ufuncs `sin()`, `cos()` `tan()` and take values in radians and produce the corresponding sin, cos, and tan values.

In [49]:
import numpy as np

In [50]:
x = np.sin(np.pi / 2)
x

np.float64(1.0)

In [51]:
x = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5, np.pi / 1000])
x = np.sin(x)
x

array([1.        , 0.8660254 , 0.70710678, 0.58778525, 0.00314159])

#### Convert Degrees into Radians

In [52]:
a = np.array([90, 180, 270, 360])
x = np.deg2rad(a)
x

array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

#### Conver Radians to Degrees

In [53]:
a = np.array([np.pi / 2, np.pi, 1.5*np.pi,  2*np.pi])
x = np.rad2deg(a)
x

array([ 90., 180., 270., 360.])

#### Finding Angles

In [60]:
# cos(angle) = values
# arccos(values) = angle
# across(cos(angle)) = angle
a = np.cos(np.pi)

b = np.arccos(np.cos(np.pi))

b

np.float64(3.141592653589793)

#### Finding Hypotenues

In [61]:
a = 2
b = 2
c = np.hypot(a, b)
c

np.float64(2.8284271247461903)