# NumPy Set Operations


In [3]:
import numpy as np
import time

In [4]:
a = np.array([1, 2, 3, 4, 5, 5, 5, 5, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 4, 5])
x = np.unique(a)
x

array([1, 2, 3, 4, 5])

#### Finding Union
+ To find the unique values of two arrays, use `union1d()` method

In [5]:
a = np.array([1, 1, 1, 1, 2, 2, 3, 4, 5, 6, 7, 8])
b = np.array([1, 1, 1, 1, 12, 12, 3, 4, 5, 6, 7, 8])
c = np.union1d(a, b)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8, 12])

#### Finding Intersection

In [6]:
a = np.array([3, 42, 5, 6])
b = np.array([3, 4, 5, 6])
c = np.intersect1d(a, b, assume_unique=True)
c

array([3, 5, 6])

#### Finding difference

In [7]:
# Find the difference of the `a` from `b`:

a = np.array([3, 42, 5, 6])
b = np.array([3, 4, 5, 6])
c = np.setdiff1d(a, b, assume_unique=True)
c

array([42])

#### Finding Symmetric Difference


In [8]:
# Find the symmetric difference of the `a` from `b`:

a = np.array([3, 42, 5, 6])
b = np.array([3, 4, 5, 6])
c = np.setxor1d(a, b, assume_unique=True)
c

array([ 4, 42])

In [9]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([1,2,3,4,5,6,7])
c = np.array([1,2,3,4,5,6,7])

x = np.concatenate([a, b, c])
print(a.shape)
x

(7,)


array([1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7, 1, 2, 3, 4, 5, 6, 7])