# Simple Arithmetic


In [1]:
import numpy as np

In [2]:
a = np.array([10, 11, 12, 13, 14, 15])
b = np.array([20, 21, 22, 23, 24, 25])
c = np.add(a, b)
a


array([10, 11, 12, 13, 14, 15])

In [4]:
a = np.array([10, 11, 12, 13, 14, 15])
b = np.array([20, 21, 22, 23, 24, 25])
c = np.subtract(a, b)
c


array([-10, -10, -10, -10, -10, -10])

In [6]:
a = np.array([10, 11, 12, 13, 14, 15])
b = np.array([20, 21, 22, 23, 24, -25])
c = np.multiply(a, b)
c


array([ 200,  231,  264,  299,  336, -375])

In [8]:
a = np.array([10, 11, 12, 13, 14, 15])
b = np.array([20, 21, 22, 23, 24, -25])
c = np.divide(a, b)
c


array([ 0.5       ,  0.52380952,  0.54545455,  0.56521739,  0.58333333,
       -0.6       ])

In [12]:
a = np.array([2] * 6)
b = np.array([2, 3, 4, 5, 6, 7])
c = np.power(a, b)
c


array([  4,   8,  16,  32,  64, 128])

In [14]:
a = np.array([4] * 6)
b = np.array([2, 3, 2, 2, 2, 2])
c = np.mod(a, b)
c


array([0, 1, 0, 0, 0, 0])

In [15]:
a = np.array([4] * 6)
b = np.array([2, 3, 2, 2, 2, 2])
c = np.remainder(a, b)
c


array([0, 1, 0, 0, 0, 0])

In [17]:
a = np.array([10, 20, 30, 40, 50, 60])
b = np.array([3, 7, 9, 8, 2, 33])
c = np.divmod(a, b)
c


(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))

In [18]:
a = np.array([-110, -20, 30, 40, 50, 60])
c = np.absolute(a)
c


array([110,  20,  30,  40,  50,  60])