# Rounding Decimals
+ There are primarily five ways of rounding off decimals
  + truncation
  + fix
  + rounding
  + floor
  + ceil

#### Truncation
+ Remove the decimals, and return the float number closest to zero
+ Use `trucn()` and `fix()` functions

In [2]:
import numpy as np

In [3]:
a = np.trunc([-3.1666, 3.99999999999999])
a

array([-3.,  3.])

In [4]:
a = np.fix([-3.1666, 3.99999999999999])
a

array([-3.,  3.])

#### Rounding
+ The `arround()` function increments preceding digit or decimal by 1 if greater than 5 else do nothin
```python
np.around(a, decimals=0)
```
+ a: the number need around
+ decimals: the number of decimal places to round to

In [5]:
a = np.around(3.106666, 2)
print(a)


3.11


In [6]:
a = np.around(5.93)
print(a)

6.0


#### Floor
+ The `floor()` function rounds off decimal to nearest lower int
+ Floor of 3.155 is 3

In [7]:
a = np.floor([-3.1666, 3.9997])

a

array([-4.,  3.])

#### Ceil
+ The `ceil()` function rounds off decimal to nearest upper int

In [8]:
a = np.ceil([-3.4444, 3.111, 9.9995])
a

array([-3.,  4., 10.])