# NumPy Logs


In [32]:
import numpy as np
import math

#### Log base 2 `log2()`

In [33]:
a = np.arange(1, 10)
np.log2(a)


array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

#### Log base 10 `log10()`

In [34]:
a = np.arange(1, 10)
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

#### Log base $e$ `log()`

In [35]:
a = np.arange(1, 10)
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
a = math.log(1e18, 2)
a

59.794705707972525

In [40]:
nplog = np.frompyfunc(log, 2, 1)
a = nplog(1e18, 2)
a

59.794705707972525