# Numpy Summations

In [24]:
import numpy as np

In [31]:
a = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
c = np.sum(a)
c

np.int64(20)

#### Summation Over an Axis
+ If you specify `axis=1`, Summing across rows.
+ If yoy specify `axis=0`, Summing across columns.

In [25]:
a = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
c = np.sum(a, axis=1)
print(c)

[10 10]


In [26]:
a = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])
c = np.sum(a, axis=0)
print(c)

[2 4 6 8]


In [27]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
c = np.sum([a, b], axis=1)
print(c)

[10 10]


In [28]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
c = np.sum([a, b], axis=0)
print(c)

[2 4 6 8]


#### Camulative Sum

In [33]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
x = np.cumsum([a, b])
x

array([ 1,  3,  6,  7,  9, 12])

In [34]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
x = np.cumsum([a, b], axis=1)
x

array([[1, 3, 6],
       [1, 3, 6]])

In [35]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
x = np.cumsum([a, b], axis=0)
x

array([[1, 2, 3],
       [2, 4, 6]])

In [30]:
a = np.array([1, 2, 3, 4])
c = np.cumsum(a)
c

array([ 1,  3,  6, 10])