# NumPy Products


In [23]:
import numpy as np

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
x = np.prod([a, b])
x

np.int64(720)

#### Product Over an Axis
+ If you specify `axis=1`, calculate the product **across each row**.
+ If you specify `axis=0`, calculate the product **down each column**.

In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
x = np.prod([a, b], axis=0)
x

array([ 4, 10, 18])

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
x = np.prod([a, b], axis=1)
x

array([  6, 120])

#### Cummulative Product

In [27]:
a = np.array([1, 2, 3, 4])
x = np.cumprod(a)
x

array([ 1,  2,  6, 24])

In [30]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
x = np.cumprod([a, b])
x

array([ 1,  2,  6,  6, 12, 36])

In [28]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
x = np.cumprod([a, b], axis=1)
x

array([[1, 2, 6],
       [1, 2, 6]])

In [29]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3])
x = np.cumprod([a, b], axis=0)
x

array([[1, 2, 3],
       [1, 4, 9]])