# Numpy Creating Arrays

In [41]:
import numpy as np

#### 1 - D arrays

In [42]:
arr = np.array([1, 2, 3, 4, 5])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


#### 2 - D arrays

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


#### 3 - D arrays

In [44]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Check number of Dimensions

In [45]:
a = np.array(12)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]], [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)


0
1
2
3
4
