In [34]:
import numpy as np

#### Searching Arrays
+ Search an a array for a certain value, and return the indexs that get match.
+ To search an array, use `where()` method

In [35]:
arr = np.array([1, 2, 3, 4, 4, 6, 7])
even = np.where(arr % 2 == 0)
odd = np.where(arr & 1)
x = np.where(arr == 4)
print(even)
print(odd)
print(x)

(array([1, 3, 4, 5]),)
(array([0, 2, 6]),)
(array([3, 4]),)


+ `searchsorted()` like binary search

In [36]:
arr = np.array([6, 7, 7, 7, 7, 8, 9])
x = np.searchsorted(arr, 7, side='left')
print(x)

1


In [37]:
arr = np.array([6, 7, 7, 7, 7, 8, 9])
x = np.searchsorted(arr, 7, side='left')
print(x)

1


#### Multiple Values
+ When we use `searchsorted()`, if the value does not exist in the array, the function will return the index where this value should be inserted to keep the array sorted.


In [38]:
arr = np.array([1, 3, 5, 7, 7, 7, 11])
x = np.searchsorted(arr, [2, 5, 9, 11])
print(x)

[1 2 6 6]
