# NumPy Coppy vs View
+ The copy is a new array
+ The view is just view of the original array

In [23]:
import numpy as np

In [24]:
arr1 = np.array([1, 2, 3])
a = arr1.copy()

arr2 = np.array([1, 2, 3])
b = arr2.view()

a[0] = 111
b[0] = 111
print(arr1) 
print(a.base)
print(arr2) 
print(b.base)


[1 2 3]
None
[111   2   3]
[111   2   3]
