# NumPy Joining Array

#### Joining NumPy Arrays
+ Joining means putting conects of two or more arrays in a single array
+ In SQL we join tables based on a key, numpy we join arrays by axes


In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 1 2 3]


In [ ]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[11, 22, 33],[44, 55, 66]])
# axis = 1, nối theo trục ngan
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[ 1  2  3 11 22 33]
 [ 4  5  6 44 55 66]]


In [5]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[11, 22, 33],[44, 55, 66]])
arr = np.stack((arr1, arr2), axis=1)
arr

array([[[ 1,  2,  3],
        [11, 22, 33]],

       [[ 4,  5,  6],
        [44, 55, 66]]])

In [7]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6 7 8]
