# Random Numbers in NumPy



In [2]:
import numpy as np
from numpy import random

#### What is random number ?
+ Random number does NOT mean a difference number every time. Random means somthing that can not predict logically

#### Generate Random Number


In [3]:
# generated a random interger from 1 to 100
x = random.randint(100)
print(x)

98


In [4]:
# generated a random float from 0 to 1
x = random.rand()
print(x)

0.933398773310677


In [5]:
# generated 1D array containing 10 random integers from 1 to 1000
arr = random.randint(1000, size=(10))
print(arr)

[593 924  90 670 757 353 933 422  70 814]


In [6]:
# generated 2D array with the shape is (3, 5) containing intergers from 1 to 10
arr = random.randint(10, size=(3, 5))
print(arr)

[[7 8 4 9 8]
 [7 8 6 3 7]
 [6 1 1 8 2]]


In [7]:
arr = random.rand(10)
print(arr)

[0.52465468 0.4605819  0.92416887 0.39738963 0.95902186 0.71945062
 0.40700483 0.16599963 0.69385479 0.31948894]


In [8]:
arr = random.rand(3, 2)
print(arr)

[[0.8680192  0.04080814]
 [0.32458217 0.79339993]
 [0.58216317 0.56336366]]


In [9]:
x = random.choice([1, 2, 3, 4, 5, 6])
print(x)

4


In [10]:
x = random.choice([3, 4, 5, 6, 7], size=(2, 5))
print(x)

[[3 6 4 6 3]
 [5 3 4 7 3]]
