# Random Data Distribution


#### What is Data Distribution?
+ Data distribution is a list of possible values, and how often each value occurs.
#### Random Distribution 
+ A random distribution is a set of random numbers that follow a certain probability density function.
+ We can generate random numbers based on defined probability using the `choice()` method of the `random` module.
+ The `choice()` method allows us to specify the probability for each value.
+ The probability is a set number between 0 and 1, where 0 means that value will never occur and 1 means that value will always occur.



In [12]:
import numpy as np
from numpy import random

In [16]:
x = random.choice([1, 2, 3, 4, 5], p=[0.1, 0.5, 0.2, 0.1, 0.1], size=(10))
print(x)

[2 2 5 2 2 4 2 2 3 3]


In [15]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[7 7 7 7 5]
 [7 3 7 5 7]
 [5 5 3 7 7]]
