# Random Permutations of Elements


In [18]:
import numpy as np
from numpy import random

#### Shuffling Arrays
+ shuffling means changing arrangement of elements in-places, another word in the array itself
+ The `shuffle()` method makes changes to the orginal array
+ The `permutation()` method does not change to the orginal array

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
random.shuffle(arr)
print(arr)

[8 3 7 5 6 2 1 4]


In [22]:
arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))
print(arr)

[5 2 3 4 1]
[1 2 3 4 5]
